<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DuckDB.NET.Data.Full" Version="1.5.5" />
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="10.3.4" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.12.0" />
    <PackageReference Include="MySql.Data" Version="26.7.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.301" />
  </ItemGroup>

</Project>
